<?php
return array (
  '/' => 
  array (
    'id' => 1,
    'uri' => '/',
    'file_path' => 'views/public/general/inicio.php',
    'layout_type' => 'public',
    'menu_group' => 'General',
    'menu_title' => 'Inicio',
    'name_file' => 'inicio',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/',
  ),
  '/admin/login' => 
  array (
    'id' => 2,
    'uri' => '/admin/login',
    'file_path' => 'views/public/general/login.php',
    'layout_type' => 'public',
    'menu_group' => 'General',
    'menu_title' => 'login',
    'name_file' => 'login',
    'show_in_menu' => 0,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/admin/login',
  ),
  '/admin/dashboard' => 
  array (
    'id' => 3,
    'uri' => '/admin/dashboard',
    'file_path' => 'views/private/dashboard.php',
    'layout_type' => 'private',
    'menu_group' => 'Principal',
    'menu_title' => 'dashboard',
    'name_file' => 'dashboard',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/dashboard',
  ),
  '/admin/usuarios' => 
  array (
    'id' => 4,
    'uri' => '/admin/usuarios',
    'file_path' => 'views/private/usuarios.php',
    'layout_type' => 'private',
    'menu_group' => 'Administración',
    'menu_title' => 'Gestión de Usuarios',
    'name_file' => 'vista_4',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/usuarios',
  ),
  '/admin/vistas/crear' => 
  array (
    'id' => 5,
    'uri' => '/admin/vistas/crear',
    'file_path' => 'views/private/vistas/crear.php',
    'layout_type' => 'private',
    'menu_group' => 'Vistas',
    'menu_title' => 'Crear Vista',
    'name_file' => 'crear',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 19:36:13',
    'raw_uri' => '/vistas/crear',
  ),
  '/admin/roles/ver' => 
  array (
    'id' => 6,
    'uri' => '/admin/roles/ver',
    'file_path' => 'views/private/roles/roles_ver.php',
    'layout_type' => 'private',
    'menu_group' => 'Roles',
    'menu_title' => 'Ver',
    'name_file' => 'ver',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-25 19:58:09',
    'raw_uri' => '/roles/ver',
  ),
  '/nosotros' => 
  array (
    'id' => 7,
    'uri' => '/nosotros',
    'file_path' => 'views/public/general/nosotros.php',
    'layout_type' => 'public',
    'menu_group' => 'General',
    'menu_title' => 'nosotros',
    'name_file' => 'nosotros',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-27 10:57:34',
    'raw_uri' => '/nosotros',
  ),
  '/admin/roles/editar' => 
  array (
    'id' => 8,
    'uri' => '/admin/roles/editar',
    'file_path' => 'views/private/roles/editar.php',
    'layout_type' => 'private',
    'menu_group' => 'Roles',
    'menu_title' => 'Editar',
    'name_file' => 'editar',
    'show_in_menu' => 0,
    'is_active' => 1,
    'created_at' => '2026-09-27 18:18:52',
    'raw_uri' => '/roles/editar',
  ),
  '/admin/roles/crear' => 
  array (
    'id' => 10,
    'uri' => '/admin/roles/crear',
    'file_path' => 'views/private/roles/crear.php',
    'layout_type' => 'private',
    'menu_group' => 'Roles',
    'menu_title' => 'Crear',
    'name_file' => 'crear',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-27 18:55:33',
    'raw_uri' => '/roles/crear',
  ),
  '/admin/vistas/editar' => 
  array (
    'id' => 11,
    'uri' => '/admin/vistas/editar',
    'file_path' => 'views/private/vistas/editar.php',
    'layout_type' => 'private',
    'menu_group' => 'Vistas',
    'menu_title' => 'Editar Vista',
    'name_file' => 'editar',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-28 21:27:02',
    'raw_uri' => '/vistas/editar',
  ),
);
