<?php
return array (
  '/' => 
  array (
    'id' => 1,
    'uri' => '/',
    'file_path' => 'views/public/home.php',
    'layout_type' => 'public',
    'type_access' => 'LA',
    'authorized_user' => NULL,
    'menu_title' => 'Inicio',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-16 18:15:25',
  ),
  '/nosotros' => 
  array (
    'id' => 2,
    'uri' => '/nosotros',
    'file_path' => 'views/public/nosotros.php',
    'layout_type' => 'public',
    'type_access' => 'LA',
    'authorized_user' => NULL,
    'menu_title' => 'Nosotros',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-16 18:15:25',
  ),
  '/contacto' => 
  array (
    'id' => 3,
    'uri' => '/contacto',
    'file_path' => 'views/public/contacto.php',
    'layout_type' => 'public',
    'type_access' => 'LA',
    'authorized_user' => NULL,
    'menu_title' => 'Contacto',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-16 18:15:25',
  ),
  '/admin/dashboard' => 
  array (
    'id' => 4,
    'uri' => '/admin/dashboard',
    'file_path' => 'views/private/dashboard.php',
    'layout_type' => 'private',
    'type_access' => 'LA',
    'authorized_user' => 'AU',
    'menu_title' => 'Panel Principal',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-16 18:15:25',
  ),
  '/admin/perfil' => 
  array (
    'id' => 5,
    'uri' => '/admin/perfil',
    'file_path' => 'views/private/perfil.php',
    'layout_type' => 'private',
    'type_access' => 'LA',
    'authorized_user' => NULL,
    'menu_title' => 'Mi Perfil',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-16 18:15:25',
  ),
  '/admin/usuarios' => 
  array (
    'id' => 6,
    'uri' => '/admin/usuarios',
    'file_path' => 'views/private/usuarios.php',
    'layout_type' => 'private',
    'type_access' => 'LA',
    'authorized_user' => 'AU',
    'menu_title' => 'Gestión de Usuarios',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-16 18:15:25',
  ),
  '/admin/configuracion' => 
  array (
    'id' => 7,
    'uri' => '/admin/configuracion',
    'file_path' => 'views/private/config.php',
    'layout_type' => 'private',
    'type_access' => 'LA',
    'authorized_user' => 'AU',
    'menu_title' => 'Configuración',
    'show_in_menu' => 0,
    'is_active' => 1,
    'created_at' => '2026-09-16 18:15:25',
  ),
);
