<?php
return array (
  '/' => 
  array (
    'id' => 1,
    'uri' => '/',
    'file_path' => 'views/public/general/inicio.php',
    'layout_type' => 'public',
    'menu_group' => 'General',
    'menu_title' => 'Inicio',
    'name_file' => 'inicio',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/',
  ),
  '/admin/login' => 
  array (
    'id' => 2,
    'uri' => '/admin/login',
    'file_path' => 'views/public/general/login.php',
    'layout_type' => 'public',
    'menu_group' => 'General',
    'menu_title' => 'login',
    'name_file' => 'login',
    'show_in_menu' => 0,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/admin/login',
  ),
  '/admin/dashboard' => 
  array (
    'id' => 3,
    'uri' => '/admin/dashboard',
    'file_path' => 'views/private/dashboard.php',
    'layout_type' => 'private',
    'menu_group' => 'Principal',
    'menu_title' => 'dashboard',
    'name_file' => 'dashboard',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/dashboard',
  ),
  '/admin/usuarios/editar' => 
  array (
    'id' => 4,
    'uri' => '/admin/usuarios/editar',
    'file_path' => 'views/private/usuarios/editar.php',
    'layout_type' => 'private',
    'menu_group' => 'Usuarios',
    'menu_title' => 'Editar Usuario',
    'name_file' => 'editar',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 09:52:40',
    'raw_uri' => '/usuarios/editar',
  ),
  '/admin/vistas/crear' => 
  array (
    'id' => 5,
    'uri' => '/admin/vistas/crear',
    'file_path' => 'views/private/vistas/crear.php',
    'layout_type' => 'private',
    'menu_group' => 'Vistas',
    'menu_title' => 'Crear Vista',
    'name_file' => 'crear',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-22 19:36:13',
    'raw_uri' => '/vistas/crear',
  ),
  '/admin/roles/ver' => 
  array (
    'id' => 6,
    'uri' => '/admin/roles/ver',
    'file_path' => 'views/private/roles/roles_ver.php',
    'layout_type' => 'private',
    'menu_group' => 'Roles',
    'menu_title' => 'Ver',
    'name_file' => 'ver',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-25 19:58:09',
    'raw_uri' => '/roles/ver',
  ),
  '/nosotros' => 
  array (
    'id' => 7,
    'uri' => '/nosotros',
    'file_path' => 'views/public/general/nosotros.php',
    'layout_type' => 'public',
    'menu_group' => 'General',
    'menu_title' => 'nosotros',
    'name_file' => 'nosotros',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-27 10:57:34',
    'raw_uri' => '/nosotros',
  ),
  '/admin/roles/editar' => 
  array (
    'id' => 8,
    'uri' => '/admin/roles/editar',
    'file_path' => 'views/private/roles/editar.php',
    'layout_type' => 'private',
    'menu_group' => 'Roles',
    'menu_title' => 'Editar',
    'name_file' => 'editar',
    'show_in_menu' => 0,
    'is_active' => 1,
    'created_at' => '2026-09-27 18:18:52',
    'raw_uri' => '/roles/editar',
  ),
  '/admin/roles/crear' => 
  array (
    'id' => 10,
    'uri' => '/admin/roles/crear',
    'file_path' => 'views/private/roles/crear.php',
    'layout_type' => 'private',
    'menu_group' => 'Roles',
    'menu_title' => 'Crear Rol',
    'name_file' => 'crear',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-27 18:55:33',
    'raw_uri' => '/roles/crear',
  ),
  '/admin/vistas/editar' => 
  array (
    'id' => 11,
    'uri' => '/admin/vistas/editar',
    'file_path' => 'views/private/vistas/editar.php',
    'layout_type' => 'private',
    'menu_group' => 'Vistas',
    'menu_title' => 'Editar Vista',
    'name_file' => 'editar',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-28 21:27:02',
    'raw_uri' => '/vistas/editar',
  ),
  '/admin/grupos/ver' => 
  array (
    'id' => 12,
    'uri' => '/admin/grupos/ver',
    'file_path' => 'views/private/grupos/ver.php',
    'layout_type' => 'private',
    'menu_group' => 'Grupos',
    'menu_title' => 'Gestión de Grupos',
    'name_file' => 'ver',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-29 17:59:30',
    'raw_uri' => '/grupos/ver',
  ),
  '/admin/usuarios/crear' => 
  array (
    'id' => 13,
    'uri' => '/admin/usuarios/crear',
    'file_path' => 'views/private/usuarios/crear.php',
    'layout_type' => 'private',
    'menu_group' => 'Usuarios',
    'menu_title' => 'Crear Usuario',
    'name_file' => 'crear',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-29 20:16:35',
    'raw_uri' => '/usuarios/crear',
  ),
  '/admin/alumnos/crear' => 
  array (
    'id' => 14,
    'uri' => '/admin/alumnos/crear',
    'file_path' => 'views/private/alumnos/crear.php',
    'layout_type' => 'private',
    'menu_group' => 'Alumnos',
    'menu_title' => 'Alta de Alumno',
    'name_file' => 'crear',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-29 22:20:26',
    'raw_uri' => '/alumnos/crear',
  ),
  '/admin/alumnos/ver' => 
  array (
    'id' => 15,
    'uri' => '/admin/alumnos/ver',
    'file_path' => 'views/private/alumnos/ver.php',
    'layout_type' => 'private',
    'menu_group' => 'Alumnos',
    'menu_title' => 'Ver Alumnos',
    'name_file' => 'ver',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-30 13:24:13',
    'raw_uri' => '/alumnos/ver',
  ),
  '/admin/caja/capturar' => 
  array (
    'id' => 16,
    'uri' => '/admin/caja/capturar',
    'file_path' => 'views/private/caja/capturar.php',
    'layout_type' => 'private',
    'menu_group' => 'Caja',
    'menu_title' => 'Capturar Pago',
    'name_file' => 'capturar',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-30 14:54:19',
    'raw_uri' => '/caja/capturar',
  ),
  '/admin/precios' => 
  array (
    'id' => 17,
    'uri' => '/admin/precios',
    'file_path' => 'views/private/precios/index.php',
    'layout_type' => 'private',
    'menu_group' => 'Precios',
    'menu_title' => 'Precios',
    'name_file' => 'index',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-09-30 22:18:58',
    'raw_uri' => '/precios',
  ),
  '/admin/cargos/registrar' => 
  array (
    'id' => 18,
    'uri' => '/admin/cargos/registrar',
    'file_path' => 'views/private/cargos/registrar_cargo.php',
    'layout_type' => 'private',
    'menu_group' => 'cargos',
    'menu_title' => 'registrar cargo',
    'name_file' => 'registrar_cargo',
    'show_in_menu' => 1,
    'is_active' => 1,
    'created_at' => '2026-10-04 19:56:56',
    'raw_uri' => '/cargos/registrar',
  ),
);
